batch_size: 4           # mini-batch size (per gradient accumulation step)
final_batch_size: 16     # total effective batch size after gradient accumulation
epochs: 20
lr: 0.0001
data_dir: "/media/ck/data/coco"
num_workers: 4
device: "cuda"

